### ISSUE TITLE
Display filename in hash view

### ISSUE THREAD

**Issue by melix99** [GeopJr/Hashbrown#29]
**Is your feature request related to a problem? Please describe.**
My brain.

**Describe the solution you'd like**
Display the filename (or the path?) of the hashed file, so that people don't forget which file was chosen (useful especially when having to hash multiple files).

**Comment by GeopJr** [comment]
Agreed, however I am not sure how to display it. Using the title is useless as on desktop mode the ViewSwitcher covers it.

*(Quick mockups)*
Infobar maybe?

![hashbrown with infobar showing the filepath of the current file](https://user-images.githubusercontent.com/18014039/144909662-e28562a2-e4d6-46b8-be9e-5586ce5061cd.png)

Or perhaps a row in the hash list?

![hashbrown on the hash list view with an additional row at the top of the list with the title "filepath" and a text entry with the path of the file](https://user-images.githubusercontent.com/18014039/144911196-7680e4f5-2e98-466d-bb36-df9340c74e3d.png)

Also should it be full path or just the file name?

**Comment by melix99** [comment]
I'd suggest using an AdwStatusPage with the filename (or path, I'm still unsure what's better) as the title and the listbox as its child.

**Comment by GeopJr** [comment]
It does look better, I'll add it after the rebrand is done, thanks!

![hashbrown on the hash list view with a status page of "README.md" as title and the hash list box as a child](https://user-images.githubusercontent.com/18014039/144914364-9c559778-6f36-4878-9995-12ae4bc722d0.png)

**Comment by GeopJr** [comment]
More testing:

<details><summary>Normal case + title</summary>

![Hashbrown hashlist with a typical file name displayed as status page title on desktop](https://user-images.githubusercontent.com/18014039/145310649-35514ee5-6735-4512-9ac0-b7c6ed30f21b.png)

![Hashbrown hashlist with a typical file name displayed as status page title on mobile](https://user-images.githubusercontent.com/18014039/145310651-d14392f9-5cd9-4a5a-8c64-f87746b8e9af.png)

</details>


<details><summary>Normal case + description</summary>

![Hashbrown hashlist with a typical file name displayed as status page description on desktop](https://user-images.githubusercontent.com/18014039/145310645-320acc60-5383-44a3-8020-04904d52b989.png)

![Hashbrown hashlist with a typical file name displayed as status page description on mobile](https://user-images.githubusercontent.com/18014039/145310648-0244011b-6f31-4df2-b7cb-97c7d0ddc4ca.png)

</details>


<details><summary>Extreme case + title</summary>


![Hashbrown hashlist with a typical file name displayed as status page title on desktop](https://user-images.githubusercontent.com/18014039/145310633-47744b30-d8b0-4f7a-92e8-0e91e37076ca.png)

![Hashbrown hashlist with a typical file name displayed as status page title on mobile](https://user-images.githubusercontent.com/18014039/145310642-691efd0a-fd14-44a0-9ec2-ad9e2da544b8.png)

</details>


<details><summary>Extreme case + description</summary>

![Hashbrown hashlist with a typical file name displayed as status page description on desktop](https://user-images.githubusercontent.com/18014039/145310639-b8af3180-f83d-4212-bcb5-1b3383bc9b5c.png)

![Hashbrown hashlist with a typical file name displayed as status page description on mobile](https://user-images.githubusercontent.com/18014039/145310640-41906aa3-fb9c-4e73-b1ed-47dc45fc666d.png)

</details>

Extreme cases + titles are a bit too much, perhaps after a certain amount of characters I should add ellipsis or use description instead of text.

cc: @bertob

**Comment by melix99** [comment]
Also notice that libadwaita now uses .title-1 for the title, which is a bit smaller and bolder, so it may already look better with that.

**Comment by bertob** [comment]
I agree that using a status page title makes the most sense here. Perhaps the path could even be displayed below the name as the status page description?

**Comment by GeopJr** [comment]
(Note: .title-1 manually applied (on host) for the screenshots due to [this bug](https://gitlab.gnome.org/GNOME/gtk/-/issues/4517))

![hashbrown mobile view on hash list with status page with filename as its title and filepath as its description](https://user-images.githubusercontent.com/18014039/145445019-b17e2936-c538-481f-8c0f-3a7994487046.png)
![hashbrown desktop view on hash list with status page with filename as its title and filepath as its description](https://user-images.githubusercontent.com/18014039/145445026-7027c22d-3db6-4e42-bf69-cbc5bd4c7bd8.png)

**Comment by bertob** [comment]
Looking good!
