### ISSUE TITLE
Tools view redesign

### ISSUE THREAD

**Issue by bertob** [GeopJr/Hashbrown#34]
The current layout of the "tools" view is a bit convoluted, a few ideas:
- Rename to "Verify", or something else that's more specific to what the view actually does, and a different icon e.g. `test-pass-symbolic`from devkit
- Larger entry for the hash
- Better flow for the layout, i.e. first the instructions, then the inputs, then the result
- No verify button, just check automatically when either the hash or the file changes
- More explicit confirmation whether or not the hash matches

![image](https://user-images.githubusercontent.com/1908896/145383587-1a2c198c-3d43-4760-853d-db6a49569132.png)

**Comment by bertob** [comment]
Uh, on further inspection I totally misunderstood how this works :joy: 

The opened file being global state is not super clear right now, so I thought this view is for choosing a file to match the hash on the left, rather than both the hash and the file being matched against the file you opened.

I'll revisit the design with that in mind, but I think this experience shows that making the fact that everything is compared against the opened file more obvious should be a goal :)

**Comment by bertob** [comment]
I'd keep the file name visible on both views, since it affects both. That was probably the main thing that confused me.

To make the tools view less empty I'd move the two tools out of the combined list and make them each a centered input/button with a title above them.

With those changes + renaming tools to Verify with the check icon, I think the layout should be fine.

Hash icon: ![hash-symbolic](https://user-images.githubusercontent.com/1908896/154869103-23aff4c0-c91a-43b4-a115-206d7556289c.svg)

**Comment by GeopJr** [comment]
Last minute feedback on redesign:

<details><summary>All stages (click)</summary>
<p>

![Screenshot of Collision desktop tools view](https://user-images.githubusercontent.com/18014039/156864091-3bd74193-5d2f-4909-aa45-2565c8980604.png)
![Screenshot of Collision desktop tools view with checksum verify successful](https://user-images.githubusercontent.com/18014039/156864088-b0f9baaa-1bf9-4eeb-b19f-7890054c8142.png)
![Screenshot of Collision desktop tools view with checksum verify unsuccessful](https://user-images.githubusercontent.com/18014039/156864087-141e9f08-3a9f-41f2-a8a3-bb30e7bd939b.png)
![Screenshot of Collision desktop tools view with file verify successful](https://user-images.githubusercontent.com/18014039/156864086-a09839df-86a8-4831-a937-969a4facba0b.png)
![Screenshot of Collision desktop tools view with file verify loading](https://user-images.githubusercontent.com/18014039/156864084-8ee108bb-6cf9-4fb9-8207-b3d2f023ab4f.png)
![Screenshot of Collision desktop tools view with file verify unsuccessful](https://user-images.githubusercontent.com/18014039/156864085-ef92ae93-d143-4c90-a9ca-faab1343bf01.png)
![Screenshot of Collision mobile tools view with checksum verify successful](https://user-images.githubusercontent.com/18014039/156864082-c2f3ca75-dfe8-4d91-bef4-756ffcd077d6.png)

![Screenshot of Collision desktop tools view with file verify unsuccessful on dark mode](https://user-images.githubusercontent.com/18014039/156864697-dab3d973-0029-4279-b9d7-a3c4d16ac847.png)
![Screenshot of Collision desktop tools view with file verify unsuccessful on high contrast](https://user-images.githubusercontent.com/18014039/156864698-8bf58720-404c-4259-8b9f-40599c4134c6.png)


</p>
</details>

I went with the first design. I'm still unsure about the feedback, .success & .error make sense since it's input but the icons can also be replaced with labels below each tool.

**Comment by bertob** [comment]
Looks pretty good to me, but exept that the check in the bottom right on the checksum thing looks to be larger than 16px.

**Comment by GeopJr** [comment]
Fixed! Thanks for all the help and feedback 🙇

Closing
